name: limit-rate-checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: formatting
        run: cargo fmt -- --check
      - name: linting
        run: cargo clippy -- -D warnings
      - name: build
        run: cargo build --release
      - name: test
        run: cargo test --workspace